spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: microconfig-dev 
---
spring:
  profiles: beta
  application:
<<<<<<< HEAD:src/main/resources/application.yml
    name: microconfig-beta
=======
    name: microconfig-beta  
>>>>>>> dev:application.yml
